/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

import com.google.gwt.core.client.JavaScriptObject;

public class btCollisionDispatcher extends btDispatcher
{

	public btCollisionDispatcher(btDefaultCollisionConfiguration config)
	{
		jsObject = createObj(config.jsObject);
	}

	private native JavaScriptObject createObj(JavaScriptObject obj) /*-{
		var obj = new $wnd.Ammo.btCollisionDispatcher(obj);
		return obj;
	}-*/;

	public btPersistentManifold getManifoldByIndexInternal(int index)
	{
//		long cPtr = CollisionJNI.btCollisionDispatcher_getManifoldByIndexInternal__SWIG_0(swigCPtr, this, index);
//		return (cPtr == 0) ? null : new btPersistentManifold(cPtr, false);
		return super.getManifoldByIndexInternal(index);
	}
}
